### ISSUE TITLE
Using maven instead of sbt

### ISSUE THREAD

**Issue by pikusxtr** [Pravoru/gatling-junitrunner#1]
Hi,
Is it possible to use that runner in maven project, e.g.
I already have automated functional tests in maven/junit5 project and I would like to add Gatling tests to the same project.
Thanks for advice

**Comment by Elufimov** [comment]
This runner is not tied up to sbt or maven, its up to the IDE support of junit.

**Comment by Elufimov** [comment]
Fill free to reopen if you have further questions.
